{% set name = "pycln" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycln-{{ version }}.tar.gz
  sha256: f3a64486f813cd29da07940c4c2bb412080a23b9b0df9b0b1576c8e39ac79c44

build:
  noarch: python
  entry_points:
    - pycln = pycln.cli:app
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }},<4
    - libcst >=0.3.10
    - pathspec >=0.9.0
    - pyyaml >=5.3.1
    - tomlkit >=0.11.1
    - typer >=0.4.1

test:
  imports:
    - pycln
    - vendor
  commands:
    - pip check
    - pycln --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hadialqattan.github.io/pycln
  summary: A formatter for finding and removing unused import statements.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadialqattan
