{% set name = "pycln" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycln-{{ version }}.tar.gz
  sha256: 758cfd07f0d9711f69989bd4cef7e451e3d7166073b0c0f77d4a712dbac8b3fe

build:
  noarch: python
  entry_points:
    - pycln = pycln.cli:app
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }},<4
    - libcst >=0.3.10
    - pathspec >=0.9.0
    - pyyaml >=5.3.1
    - tomlkit >=0.11.1
    - typer >=0.4.1

test:
  imports:
    - pycln
    - vendor
  commands:
    - pip check
    - pycln --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hadialqattan.github.io/pycln
  summary: A formatter for finding and removing unused import statements.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadialqattan
