{% set name = "pycln" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycln-{{ version }}.tar.gz
  sha256: 8759b36753234c8f95895a31dde329479ffed2218f49d1a1c77c7edccc02e09b

build:
  noarch: python
  entry_points:
    - pycln = pycln.cli:app
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.0,<4
    - pip
    - poetry
  run:
    - python >=3.6.2,<4
    - libcst >=0.3.10
    - pathspec >=0.9.0
    - pyyaml >=5.3.1
    - tomlkit >=0.11.1
    - typer >=0.4.1

test:
  imports:
    - pycln
    - vendor
  commands:
    - pip check
    - pycln --help
  requires:
    - pip

about:
  home: https://hadialqattan.github.io/pycln
  summary: A formatter for finding and removing unused import statements.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadialqattan
